import {
  stringifyNginxConf,

  COMBO_MIME, DEFAULT_MIME, COMMON_MIME_MAP,
  COMMON_COMPRESS_MIME_LIST,
  COMBO_COMPRESS, COMBO_GZIP, COMBO_BROTLI,
  COMBO_GZIP_STATIC, COMBO_BROTLI_STATIC, COMBO_COMPRESS_STATIC
} from 'source/common/config/Nginx.js'

/** @deprecated */ const stringifyNginxConfExport = stringifyNginxConf // TODO: DEPRECATE
/** @deprecated */ const COMBO_MIME_EXPORT = COMBO_MIME // TODO: DEPRECATE
/** @deprecated */ const DEFAULT_MIME_EXPORT = DEFAULT_MIME // TODO: DEPRECATE
/** @deprecated */ const COMMON_MIME_MAP_EXPORT = COMMON_MIME_MAP // TODO: DEPRECATE
/** @deprecated */ const COMMON_COMPRESS_MIME_LIST_EXPORT = COMMON_COMPRESS_MIME_LIST // TODO: DEPRECATE
/** @deprecated */ const COMBO_COMPRESS_EXPORT = COMBO_COMPRESS // TODO: DEPRECATE
/** @deprecated */ const COMBO_GZIP_EXPORT = COMBO_GZIP // TODO: DEPRECATE
/** @deprecated */ const COMBO_BROTLI_EXPORT = COMBO_BROTLI // TODO: DEPRECATE
/** @deprecated */ const COMBO_GZIP_STATIC_EXPORT = COMBO_GZIP_STATIC // TODO: DEPRECATE
/** @deprecated */ const COMBO_BROTLI_STATIC_EXPORT = COMBO_BROTLI_STATIC // TODO: DEPRECATE
/** @deprecated */ const COMBO_COMPRESS_STATIC_EXPORT = COMBO_COMPRESS_STATIC // TODO: DEPRECATE

export {
  stringifyNginxConfExport as stringifyNginxConf,
  COMBO_MIME_EXPORT as COMBO_MIME,
  DEFAULT_MIME_EXPORT as DEFAULT_MIME,
  COMMON_MIME_MAP_EXPORT as COMMON_MIME_MAP,
  COMMON_COMPRESS_MIME_LIST_EXPORT as COMMON_COMPRESS_MIME_LIST,
  COMBO_COMPRESS_EXPORT as COMBO_COMPRESS,
  COMBO_GZIP_EXPORT as COMBO_GZIP,
  COMBO_BROTLI_EXPORT as COMBO_BROTLI,
  COMBO_GZIP_STATIC_EXPORT as COMBO_GZIP_STATIC,
  COMBO_BROTLI_STATIC_EXPORT as COMBO_BROTLI_STATIC,
  COMBO_COMPRESS_STATIC_EXPORT as COMBO_COMPRESS_STATIC
}
