name: ci-test

on:
  push:
    branches:
      - '**'

jobs:
  build:
    strategy:
      fail-fast: false # allow all test to run to the end
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        node-version: [ 14.x, 15.x ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Reset Git config # fix win32 CI cause `something to commit` test error: https://github.com/actions/checkout/issues/135#issuecomment-602171132
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Setup Git repo
        uses: actions/checkout@v2 # https://github.com/actions/checkout

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1 # https://github.com/actions/setup-node
        with:
          node-version: ${{ matrix.node-version }}

      - name: Log CI info
        run: |
          echo "system: $(node -p "os.platform() + ' - ' + os.release() + ' [' + os.arch() + ']'")"
          echo "node: $(node -v)"
          echo "npm: $(npm -v)"

      - run: npx @dr-js/dev@0.4.1-dev.4 -c .github/ci-cache/cache-step.config.js --cache-step setup

      - name: Cache JS
        uses: actions/cache@v2 # https://github.com/actions/cache
        env:
          cache-version: 20201125
        with:
          key: ${{ runner.os }}-${{ env.cache-version }}-${{ matrix.node-version }}-${{ hashFiles('.github/ci-cache/temp-gitignore/cache-step-checksum-file') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-version }}-${{ matrix.node-version }}-
          path: |
            ~/.npm/
            node_modules/
            .github/ci-cache/persist-gitignore/

      - run: npx @dr-js/dev@0.4.1-dev.4 -c .github/ci-cache/cache-step.config.js --cache-step mark

      - run: npm ci

      - run: npm run script-pack-test

      - run: npx @dr-js/dev@0.4.1-dev.4 -c .github/ci-cache/cache-step.config.js --cache-step prune
